//
// Created by Sean Grady on 2/9/2022.
//
//class that holds vectors of each tweet inputted as well as reads all files in and is used to analyze the data and print to output file
#ifndef PA01_SENTIMENT_TWEETSET_H
#define PA01_SENTIMENT_TWEETSET_H
#include <iostream>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <vector>
#include "Tweet.h"
#include "DSString.h"
using namespace std;
class TweetSet {
private:


    //vectors to hold all tweets
    vector<Tweet> testingTweet;
    vector<Tweet> trainingTweet;
    vector<Tweet> finalTweet;
    vector<Tweet> incorrect;
    //holds total incorrect tweets and the accuracy of the program
    int totalCorrect = 0;
    double accuracy = 0;

public:
    //object that holds all words generated by training set
    words allWords;

    //passing in tweets with no IDS
    TweetSet(int argc, char **argv);
    //finds tweet by searching by ID
    bool findTweet(int);
    //analyzes the correct tweets and incorrect tweet sentiments
    double analyze();

};


#endif //PA01_SENTIMENT_TWEETSET_H
